PLSQL SET 15
Write a program that will prompt for a EMPNO,ENAME,SAL.If EMPNO does not exists in EMP table then INSERT the EMPNO,ENAME,SAL into the EMP table else UPDATE NAME,SAL for that EMPNO.


CREATE TABLE EMP(
EMPNO NUMBER PRIMARY KEY,
ENAME VARCHAR2(20),
SAL NUMBER
);
INSERT INTO EMP
VALUES(101,'OM',50000);
INSERT INTO EMP
VALUES(102,'KRUSHNA',40000);
DECLARE
V_EMPNO EMP.EMPNO%TYPE:=&EMPNO;
V_ENAME EMP.ENAME%TYPE:='&ENAME';
V_SAL EMP.SAL%TYPE:=&SAL;
CNT NUMBER;
BEGIN
SELECT COUNT(*)
INTO CNT
FROM EMP
WHERE EMPNO=V_EMPNO;
IF CNT=0 THEN
INSERT INTO EMP
VALUES(V_EMPNO,V_ENAME,V_SAL);
DBMS_OUTPUT.PUT_LINE('RECORD INSERTED');
ELSE
UPDATE EMP
SET ENAME=V_ENAME,
SAL=V_SAL
WHERE EMPNO=V_EMPNO;
DBMS_OUTPUT.PUT_LINE('RECORD UPDATED');
END IF;
END;
/


PLSQL SET 16
Write a program that will prompt for number and display whether the number is ODD or EVEN number.Add user defined exception to check the number is negative.


DECLARE
NUM NUMBER:=&NUM;
NEGATIVE EXCEPTION;
BEGIN
IF NUM<0 THEN
RAISE NEGATIVE;
END IF;
IF MOD(NUM,2)=0 THEN
DBMS_OUTPUT.PUT_LINE('EVEN NUMBER');
ELSE
DBMS_OUTPUT.PUT_LINE('ODD NUMBER');
END IF;
EXCEPTION
WHEN NEGATIVE THEN
DBMS_OUTPUT.PUT_LINE('NEGATIVE NUMBER NOT ALLOWED');
END;
/


PLSQL SET 17
Write program that prompts for EMPNO and update his salary based on the below specification: If the employee belongs to DEPTNO 10 then update his salary by 10%.



CREATE TABLE EMP(
EMPNO NUMBER PRIMARY KEY,
ENAME VARCHAR2(20),
SAL NUMBER,
COMM NUMBER,
DEPTNO NUMBER
);
INSERT INTO EMP
VALUES(101,'OM',50000,2000,10);
INSERT INTO EMP
VALUES(102,'KRUSHNA',40000,3000,20);

INSERT INTO EMP
VALUES(103,'RAHUL',35000,4000,30);
DECLARE
V_EMPNO EMP.EMPNO%TYPE:=&EMPNO;
V_DEPTNO EMP.DEPTNO%TYPE;
V_SAL EMP.SAL%TYPE;
V_COMM EMP.COMM%TYPE;
BEGIN
SELECT DEPTNO,SAL,COMM
INTO V_DEPTNO,V_SAL,V_COMM
FROM EMP
WHERE EMPNO=V_EMPNO;
IF V_DEPTNO=10 THEN
UPDATE EMP
SET SAL=SAL+(SAL*0.10)
WHERE EMPNO=V_EMPNO;
DBMS_OUTPUT.PUT_LINE('10 PERCENT SALARY UPDATED');
ELSIF V_DEPTNO=20 THEN
UPDATE EMP
SET SAL=SAL+(SAL*0.15)
WHERE EMPNO=V_EMPNO;
DBMS_OUTPUT.PUT_LINE('15 PERCENT SALARY UPDATED');
ELSE
UPDATE EMP
SET SAL=SAL+COMM
WHERE EMPNO=V_EMPNO;
DBMS_OUTPUT.PUT_LINE('SALARY + COMM UPDATED');
END IF;
END;
/



PLSQL SET 18
Unnamed PL/SQL code block: Use of Control structure and Exception handling is mandatory. Write a PL/SQL block of code for the following requirements:-Consider table Stud(Roll, Att,Status) Write a PL/SQL block for

CREATE TABLE STUD(
ROLL NUMBER PRIMARY KEY,
ATT NUMBER,
STATUS VARCHAR2(5)
);
INSERT INTO STUD
VALUES(1,80,NULL);
INSERT INTO STUD
VALUES(2,60,NULL);
INSERT INTO STUD
VALUES(3,70,NULL);
DECLARE
V_ROLL STUD.ROLL%TYPE:=&ROLL;
V_ATT STUD.ATT%TYPE;
BEGIN
SELECT ATT
INTO V_ATT
FROM STUD
WHERE ROLL=V_ROLL;
IF V_ATT<75 THEN
UPDATE STUD
SET STATUS='D'
WHERE ROLL=V_ROLL;
DBMS_OUTPUT.PUT_LINE('TERM NOT GRANTED');
ELSE
UPDATE STUD
SET STATUS='ND'
WHERE ROLL=V_ROLL;
DBMS_OUTPUT.PUT_LINE('TERM GRANTED');
END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('ROLL NUMBER NOT FOUND');

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR OCCURRED');
END;
/


PLSQL SET 19
Unnamed PL/SQL code block: Use of Control structure and Exception handling is mandatory. Write a PL/SQL block of code for the following requirements:- Schema:

CREATE TABLE BORROWER(
ROLLIN NUMBER,
NAME VARCHAR2(20),
DATEOFISSUE DATE,
NAMEOFBOOK VARCHAR2(30),
STATUS VARCHAR2(5)
);
CREATE TABLE FINE(
ROLL_NO NUMBER,
DATE1 DATE,
AMT NUMBER
);
INSERT INTO BORROWER
VALUES(
1,
'OM',
TO_DATE('01-05-2026','DD-MM-YYYY'),
'DBMS',
'I'
);
INSERT INTO BORROWER
VALUES(
2,
'KRUSHNA',
TO_DATE('20-04-2026','DD-MM-YYYY'),
'CN',
'I'
);
DECLARE
V_ROLL NUMBER:=&ROLL_NO;
V_BOOK VARCHAR2(30):='&BOOK_NAME';
V_DATE DATE;
V_DAYS NUMBER;
V_FINE NUMBER:=0;
BEGIN
SELECT DATEOFISSUE
INTO V_DATE
FROM BORROWER
WHERE ROLLIN=V_ROLL
AND NAMEOFBOOK=V_BOOK;
V_DAYS:=SYSDATE-V_DATE;
IF V_DAYS BETWEEN 15 AND 30 THEN
V_FINE:=V_DAYS*5;
ELSIF V_DAYS>30 THEN
V_FINE:=30*5+(V_DAYS-30)*50;
END IF;
UPDATE BORROWER
SET STATUS='R'
WHERE ROLLIN=V_ROLL
AND NAMEOFBOOK=V_BOOK;
IF V_FINE>0 THEN
INSERT INTO FINE
VALUES(V_ROLL,SYSDATE,V_FINE);
END IF;
DBMS_OUTPUT.PUT_LINE('FINE AMOUNT IS '||V_FINE);
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('RECORD NOT FOUND');

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR OCCURRED');
END;
/


PLSQL SET 21
Write a program that displays the Top N salaries using simple Explicit Cursors.

CREATE TABLE EMP(
EMPNO NUMBER,
ENAME VARCHAR2(20),
SAL NUMBER
);
INSERT INTO EMP
VALUES(101,'OM',50000);
INSERT INTO EMP
VALUES(102,'KRUSHNA',70000);
INSERT INTO EMP
VALUES(103,'RAHUL',45000);
INSERT INTO EMP
VALUES(104,'AMIT',80000);
INSERT INTO EMP
VALUES(105,'ROHAN',60000);
DECLARE
CURSOR C1 IS
SELECT *
FROM EMP
ORDER BY SAL DESC;
V_EMPNO EMP.EMPNO%TYPE;
V_ENAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;
N NUMBER:=&N;
COUNT1 NUMBER:=0;
BEGIN

OPEN C1;
LOOP
FETCH C1
INTO V_EMPNO,V_ENAME,V_SAL;
EXIT WHEN C1%NOTFOUND OR COUNT1=N;
DBMS_OUTPUT.PUT_LINE(
V_EMPNO||' '||
V_ENAME||' '||
V_SAL
);
COUNT1:=COUNT1+1;
END LOOP;
CLOSE C1;
END;
/


PLSQL SET 22
PL/SQL Stored Procedure. Write a Stored Procedure namely proc_Grade for the categorization of student. If marks scored by students in examination is <=1500 and marks>=990 then student will be placed in distinction category if 

CREATE TABLE STUD_MARKS(
ROLL NUMBER,
NAME VARCHAR2(20),
TOTAL_MARKS NUMBER
);
CREATE TABLE RESULT(
ROLL NUMBER,
NAME VARCHAR2(20),
CLASS VARCHAR2(30)
);
INSERT INTO STUD_MARKS
VALUES(1,'OM',1200);
INSERT INTO STUD_MARKS
VALUES(2,'KRUSHNA',950);

INSERT INTO STUD_MARKS
VALUES(3,'RAHUL',850);
CREATE OR REPLACE PROCEDURE PROC_GRADE(
P_ROLL NUMBER,
P_NAME VARCHAR2,
P_MARKS NUMBER
)
IS
V_CLASS VARCHAR2(30);
BEGIN
IF P_MARKS<=1500 AND P_MARKS>=990 THEN
V_CLASS:='DISTINCTION';
ELSIF P_MARKS BETWEEN 900 AND 989 THEN
V_CLASS:='FIRST CLASS';
ELSIF P_MARKS BETWEEN 825 AND 899 THEN
V_CLASS:='HIGHER SECOND CLASS';
ELSE
V_CLASS:='FAIL';
END IF;
INSERT INTO RESULT
VALUES(P_ROLL,P_NAME,V_CLASS);
END;
/
BEGIN
PROC_GRADE(1,'OM',1200);
PROC_GRADE(2,'KRUSHNA',950);
PROC_GRADE(3,'RAHUL',850);
END;
/
SELECT * FROM RESULT;




PLSQL SET 25
Write a database trigger on Library table. The System should keep track of the records that are being updated or deleted. The old value of updated or deleted records should be added in

CREATE TABLE LIBRARY(
BOOK_ID NUMBER,
BOOK_NAME VARCHAR2(30),
AUTHOR VARCHAR2(30),
PRICE NUMBER
);
CREATE TABLE LIBRARY_AUDIT(
BOOK_ID NUMBER,
BOOK_NAME VARCHAR2(30),
AUTHOR VARCHAR2(30),
PRICE NUMBER,
ACTION VARCHAR2(20),
ACTION_DATE DATE
);
INSERT INTO LIBRARY
VALUES(1,'DBMS','KORTH',500);
INSERT INTO LIBRARY
VALUES(2,'CN','FOROUZAN',450);
INSERT INTO LIBRARY
VALUES(3,'OS','GALVIN',600);
CREATE OR REPLACE TRIGGER TRG_LIBRARY
BEFORE UPDATE OR DELETE
ON LIBRARY
FOR EACH ROW
BEGIN
IF UPDATING THEN
INSERT INTO LIBRARY_AUDIT
VALUES(
:OLD.BOOK_ID,
:OLD.BOOK_NAME,
:OLD.AUTHOR,
:OLD.PRICE,
'UPDATED',
SYSDATE
);
ELSIF DELETING THEN
INSERT INTO LIBRARY_AUDIT
VALUES(
:OLD.BOOK_ID,
:OLD.BOOK_NAME,
:OLD.AUTHOR,
:OLD.PRICE,
'DELETED',
SYSDATE
);
END IF;
END;
/
UPDATE LIBRARY
SET PRICE=700
WHERE BOOK_ID=1;
DELETE FROM LIBRARY
WHERE BOOK_ID=2;
SELECT * FROM LIBRARY;
SELECT * FROM LIBRARY_AUDIT;
