SQL Set 1
-- Create PERSON table
CREATE TABLE PERSON(
    DRIVER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(30),
    ADDRESS VARCHAR2(50)
);

-- Create CAR table
CREATE TABLE CAR(
    LICENSE VARCHAR2(20) PRIMARY KEY,
    MODEL VARCHAR2(20),
    YEAR NUMBER
);

-- Create ACCIDENT table
CREATE TABLE ACCIDENT(
    REPORT_NO NUMBER PRIMARY KEY,
    DATE_ACC DATE,
    LOCATION VARCHAR2(30)
);

-- Create OWNS table
CREATE TABLE OWNS(
    DRIVER_ID NUMBER,
    LICENSE VARCHAR2(20),
    FOREIGN KEY(DRIVER_ID)
    REFERENCES PERSON(DRIVER_ID),
    FOREIGN KEY(LICENSE)
    REFERENCES CAR(LICENSE)
);



-- Create PARTICIPATED table
CREATE TABLE PARTICIPATED(
    DRIVER_ID NUMBER,
    MODEL VARCHAR2(20),
    REPORT_NO NUMBER,
    DAMAGE_AMOUNT NUMBER,
    FOREIGN KEY(REPORT_NO)
    REFERENCES ACCIDENT(REPORT_NO)
);

-- Insert 5 records into PERSON
INSERT INTO PERSON VALUES(1,'OM','PUNE');
INSERT INTO PERSON VALUES(2,'KRUSHNA','MUMBAI');
INSERT INTO PERSON VALUES(3,'RAHUL','NAGAR');
INSERT INTO PERSON VALUES(4,'AMIT','NASHIK');
INSERT INTO PERSON VALUES(5,'ROHAN','SATARA');

-- Insert 5 records into CAR
INSERT INTO CAR VALUES('MH12AB1234','SWIFT',2020);
INSERT INTO CAR VALUES('MH14XY5678','I20',2021);
INSERT INTO CAR VALUES('MH15PQ4567','HONDA',2022);
INSERT INTO CAR VALUES('MH11AA1111','BMW',2023);
INSERT INTO CAR VALUES('MH13BB2222','AUDI',2024);

-- Insert 5 records into ACCIDENT
INSERT INTO ACCIDENT
VALUES(1,TO_DATE('10-01-2024','DD-MM-YYYY'),'PUNE');

INSERT INTO ACCIDENT
VALUES(2,TO_DATE('11-02-2024','DD-MM-YYYY'),'MUMBAI');

INSERT INTO ACCIDENT
VALUES(3,TO_DATE('12-03-2024','DD-MM-YYYY'),'NAGAR');

INSERT INTO ACCIDENT
VALUES(4,TO_DATE('13-04-2024','DD-MM-YYYY'),'NASHIK');

INSERT INTO ACCIDENT
VALUES(5,TO_DATE('14-05-2024','DD-MM-YYYY'),'SATARA');

-- Insert 5 records into OWNS
INSERT INTO OWNS VALUES(1,'MH12AB1234');
INSERT INTO OWNS VALUES(2,'MH14XY5678');
INSERT INTO OWNS VALUES(3,'MH15PQ4567');
INSERT INTO OWNS VALUES(4,'MH11AA1111');
INSERT INTO OWNS VALUES(5,'MH13BB2222');

-- Insert 5 records into PARTICIPATED
INSERT INTO PARTICIPATED VALUES(1,'SWIFT',1,15000);
INSERT INTO PARTICIPATED VALUES(2,'I20',2,12000);
INSERT INTO PARTICIPATED VALUES(3,'HONDA',3,20000);
INSERT INTO PARTICIPATED VALUES(4,'BMW',4,30000);
INSERT INTO PARTICIPATED VALUES(5,'AUDI',5,50000);

-- Display schema of each table
DESC PERSON;
DESC CAR;
DESC ACCIDENT;
DESC OWNS;
DESC PARTICIPATED;

-- Display all records from PERSON table
SELECT * FROM PERSON;

-- Set foreign key constraint
ALTER TABLE PARTICIPATED
ADD CONSTRAINT FK_REPORT
FOREIGN KEY(REPORT_NO)
REFERENCES ACCIDENT(REPORT_NO);

-- Add check constraint on DAMAGE_AMOUNT
ALTER TABLE PARTICIPATED
ADD CONSTRAINT CHK_DAMAGE
CHECK(DAMAGE_AMOUNT>=0);

-- Make NAME column NOT NULL
ALTER TABLE PERSON
MODIFY NAME VARCHAR2(30) NOT NULL;

-- Rename CAR table to VEHICLE
RENAME CAR TO VEHICLE;

-- Create NEW_PERSON table from PERSON
CREATE TABLE NEW_PERSON
AS
SELECT *
FROM PERSON;

-- Drop NEW_PERSON table
DROP TABLE NEW_PERSON;

SQL SET 2
-- Create CUSTOMER table
CREATE TABLE CUSTOMER(
    C_ID NUMBER PRIMARY KEY,
    CNAME VARCHAR2(20),
    CITY VARCHAR2(20)
);

-- Create ACCOUNT table
CREATE TABLE ACCOUNT(
    C_ID NUMBER,
    ACC_TYPE VARCHAR2(20),
    AMOUNT NUMBER,
    FOREIGN KEY(C_ID)
    REFERENCES CUSTOMER(C_ID)
);

-- Insert records into CUSTOMER
INSERT INTO CUSTOMER VALUES(1,'John','Nashik');
INSERT INTO CUSTOMER VALUES(2,'Seema','Aurangabad');
INSERT INTO CUSTOMER VALUES(3,'Amita','Nagar');
INSERT INTO CUSTOMER VALUES(4,'Rakesh','Pune');
INSERT INTO CUSTOMER VALUES(5,'Samata','Nashik');
INSERT INTO CUSTOMER VALUES(6,'Ankita','Chandwad');
INSERT INTO CUSTOMER VALUES(7,'Bhavika','Pune');
INSERT INTO CUSTOMER VALUES(8,'Deepa','Mumbai');
INSERT INTO CUSTOMER VALUES(9,'Nitin','Nagpur');
INSERT INTO CUSTOMER VALUES(10,'Pooja','Pune');

-- Insert records into ACCOUNT
INSERT INTO ACCOUNT VALUES(1,'Current',5000);
INSERT INTO ACCOUNT VALUES(2,'Saving',20000);
INSERT INTO ACCOUNT VALUES(3,'Saving',70000);
INSERT INTO ACCOUNT VALUES(4,'Saving',50000);
INSERT INTO ACCOUNT VALUES(6,'Current',35000);
INSERT INTO ACCOUNT VALUES(7,'Loan',30000);
INSERT INTO ACCOUNT VALUES(8,'Saving',50000);
INSERT INTO ACCOUNT VALUES(9,'Saving',90000);
INSERT INTO ACCOUNT VALUES(10,'Loan',8000);
INSERT INTO ACCOUNT VALUES(11,'Current',45000);

-- 1. Show cname, acc_type and amount of customer having saving account
SELECT CNAME,ACC_TYPE,AMOUNT
FROM CUSTOMER
NATURAL JOIN ACCOUNT
WHERE ACC_TYPE='Saving';

-- 2. Display data using natural, left and right join
SELECT *
FROM CUSTOMER
NATURAL JOIN ACCOUNT;

SELECT *
FROM CUSTOMER
LEFT JOIN ACCOUNT
ON CUSTOMER.C_ID=ACCOUNT.C_ID;

SELECT *
FROM CUSTOMER
RIGHT JOIN ACCOUNT
ON CUSTOMER.C_ID=ACCOUNT.C_ID;

-- 3. Display customers living in same city as Pooja
SELECT *
FROM CUSTOMER
WHERE CITY=
(
SELECT CITY
FROM CUSTOMER
WHERE CNAME='Pooja'
);

-- 4. Display account information having amount less than average amount
SELECT *
FROM ACCOUNT
WHERE AMOUNT<
(
SELECT AVG(AMOUNT)
FROM ACCOUNT);

-- 5. Display C_ID having maximum amount
SELECT C_ID
FROM ACCOUNT
WHERE AMOUNT=
(
SELECT MAX(AMOUNT)
FROM ACCOUNT
);

-- 6. Display amount and acc_type having minimum amount of that acc_type
SELECT ACC_TYPE,AMOUNT
FROM ACCOUNT A
WHERE AMOUNT=
(
SELECT MIN(AMOUNT)
FROM ACCOUNT
WHERE ACC_TYPE=A.ACC_TYPE
);

-- 7. Display amount of accounts whose amount is higher than any saving account amount
SELECT AMOUNT
FROM ACCOUNT
WHERE AMOUNT > ANY
(
SELECT AMOUNT
FROM ACCOUNT
WHERE ACC_TYPE='Saving'
);





SQL SET 3
-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT(
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(20),
    LOCATION VARCHAR2(20)
);

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(20),
    CITY VARCHAR2(20),
    SALARY NUMBER,
    DEPARTMENT NUMBER,
    FOREIGN KEY(DEPARTMENT)
    REFERENCES DEPARTMENT(DEPT_ID)
);

-- Display schema of each table
DESC EMPLOYEE;
DESC DEPARTMENT;

-- Insert 10 records into DEPARTMENT
INSERT INTO DEPARTMENT VALUES(1,'IT','PUNE');
INSERT INTO DEPARTMENT VALUES(2,'COMP','MUMBAI');
INSERT INTO DEPARTMENT VALUES(3,'ENTC','NAGAR');
INSERT INTO DEPARTMENT VALUES(4,'MECH','NASHIK');
INSERT INTO DEPARTMENT VALUES(5,'CIVIL','SATARA');
INSERT INTO DEPARTMENT VALUES(6,'HR','DELHI');
INSERT INTO DEPARTMENT VALUES(7,'SALES','PUNE');
INSERT INTO DEPARTMENT VALUES(8,'ADMIN','MUMBAI');
INSERT INTO DEPARTMENT VALUES(9,'ACCOUNT','NAGPUR');
INSERT INTO DEPARTMENT VALUES(10,'TEST','AURANGABAD');

-- Insert 10 records into EMPLOYEE
INSERT INTO EMPLOYEE VALUES(101,'OM','PUNE',50000,1);
INSERT INTO EMPLOYEE VALUES(102,'KRUSHNA','MUMBAI',60000,2);
INSERT INTO EMPLOYEE VALUES(103,'RAHUL','NAGAR',45000,3);
INSERT INTO EMPLOYEE VALUES(104,'AMIT','NASHIK',70000,1);
INSERT INTO EMPLOYEE VALUES(105,'ROHAN','SATARA',35000,4);
INSERT INTO EMPLOYEE VALUES(106,'NIKHIL','PUNE',40000,5);
INSERT INTO EMPLOYEE VALUES(107,'AKASH','MUMBAI',55000,1);
INSERT INTO EMPLOYEE VALUES(108,'SUMIT','DELHI',65000,6);
INSERT INTO EMPLOYEE VALUES(109,'VISHAL','NAGPUR',30000,7);
INSERT INTO EMPLOYEE VALUES(110,'SAGAR','AURANGABAD',48000,8);

-- Insert new department record
INSERT INTO DEPARTMENT
VALUES(11,'MARKETING','PUNE');

-- Insert employee record without salary column
INSERT INTO EMPLOYEE
(EMP_ID,EMP_NAME,CITY,DEPARTMENT)
VALUES
(111,'RAVI','PUNE',1);

-- Update salary of all employees by 20%
UPDATE EMPLOYEE
SET SALARY=SALARY+(SALARY*0.20);

-- Display employee name and annual salary whose second letter is e
SELECT EMP_NAME,
SALARY*12 AS ANNUAL_SALARY
FROM EMPLOYEE
WHERE EMP_NAME LIKE '_E%';


-- Update city to Pune for employees working in IT department
UPDATE EMPLOYEE
SET CITY='PUNE'
WHERE DEPARTMENT=
(
SELECT DEPT_ID
FROM DEPARTMENT
WHERE DEPT_NAME='IT'
);


SQL SET 4
-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT(
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(20),
    LOCATION VARCHAR2(20)
);

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(20),
    CITY VARCHAR2(20),
    SALARY NUMBER,
    DEPARTMENT NUMBER,
    FOREIGN KEY(DEPARTMENT)
    REFERENCES DEPARTMENT(DEPT_ID)
);

-- Display schema of each table
DESC EMPLOYEE;
DESC DEPARTMENT;

-- Insert records into DEPARTMENT
INSERT INTO DEPARTMENT VALUES(1,'IT','PUNE');
INSERT INTO DEPARTMENT VALUES(2,'COMP','MUMBAI');
INSERT INTO DEPARTMENT VALUES(3,'HR','DELHI');
INSERT INTO DEPARTMENT VALUES(4,'SALES','NASHIK');
INSERT INTO DEPARTMENT VALUES(5,'ADMIN','PUNE');
INSERT INTO DEPARTMENT VALUES(6,'MECH','NAGAR');
INSERT INTO DEPARTMENT VALUES(7,'CIVIL','SATARA');
INSERT INTO DEPARTMENT VALUES(8,'ENTC','MUMBAI');
INSERT INTO DEPARTMENT VALUES(9,'ACCOUNT','NAGPUR');
INSERT INTO DEPARTMENT VALUES(10,'TEST','PUNE');

-- Insert records into EMPLOYEE
INSERT INTO EMPLOYEE VALUES(101,'OM','PUNE',60000,1);
INSERT INTO EMPLOYEE VALUES(102,'KRUSHNA','MUMBAI',45000,2);
INSERT INTO EMPLOYEE VALUES(103,'RAHUL','NASHIK',30000,3);
INSERT INTO EMPLOYEE VALUES(104,'AMIT','PUNE',70000,1);
INSERT INTO EMPLOYEE VALUES(105,'ROHAN','MUMBAI',25000,4);
INSERT INTO EMPLOYEE VALUES(106,'NIKHIL','DELHI',80000,1);
INSERT INTO EMPLOYEE VALUES(107,'AKASH','PUNE',55000,5);
INSERT INTO EMPLOYEE VALUES(108,'SUMIT','NAGPUR',35000,6);
INSERT INTO EMPLOYEE VALUES(109,'VISHAL','MUMBAI',65000,1);
INSERT INTO EMPLOYEE VALUES(110,'SAGAR','SATARA',40000,7);

-- Update city to Pune for employees working in IT department
UPDATE EMPLOYEE
SET CITY='PUNE'
WHERE DEPARTMENT=
(
SELECT DEPT_ID
FROM DEPARTMENT
WHERE DEPT_NAME='IT'
);

-- Delete employee records whose salary is greater than 100000
DELETE FROM EMPLOYEE
WHERE SALARY>100000;

-- Display employee name and salary after deducting 5% tax
SELECT EMP_NAME,
SALARY-(SALARY*0.05) AS FINAL_SALARY
FROM EMPLOYEE;

-- Display employees who do not live in Mumbai and whose names start with A
SELECT *
FROM EMPLOYEE
WHERE CITY<>'MUMBAI'
AND EMP_NAME LIKE 'A%';

-- Display employees belonging to IT department and salary >50000
SELECT *
FROM EMPLOYEE
WHERE DEPARTMENT=
(
SELECT DEPT_ID
FROM DEPARTMENT
WHERE DEPT_NAME='IT'
)
AND SALARY>50000;


SQL SET 5
-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE(
EMPID NUMBER,
EMPNAME VARCHAR2(10)
);

-- Insert record into EMPLOYEE table
INSERT INTO EMPLOYEE
VALUES(01,'OM');

-- Create new user
CREATE USER C##CLASS_DIV_ROLLNO
IDENTIFIED BY PASSWORD;

-- Grant SELECT privilege on EMPLOYEE table
GRANT SELECT
ON EMPLOYEE
TO C##CLASS_DIV_ROLLNO;

-- Grant INSERT and UPDATE privileges
GRANT INSERT,UPDATE
ON EMPLOYEE
TO C##CLASS_DIV_ROLLNO;

-- Revoke UPDATE privilege
REVOKE UPDATE
ON EMPLOYEE
FROM C##CLASS_DIV_ROLLNO;

-- Create role
CREATE ROLE C##MANAGER_ROLE;

-- Grant SELECT and DELETE privileges to role
GRANT SELECT,DELETE
ON EMPLOYEE
TO C##MANAGER_ROLE;

-- Grant role to user
GRANT C##MANAGER_ROLE
TO C##CLASS_DIV_ROLLNO;

-- Revoke role from user
REVOKE C##MANAGER_ROLE
FROM C##CLASS_DIV_ROLLNO;


SQL SET 6

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25) NOT NULL,
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10) NOT NULL,
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4)
);

-- Create DEPARTMENTS table
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID NUMBER(4),
DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
MANAGER_ID NUMBER(6),
LOCATION_ID NUMBER(4)
);

-- Insert records into DEPARTMENTS
INSERT INTO DEPARTMENTS
VALUES(1,'IT',101,100);

INSERT INTO DEPARTMENTS
VALUES(2,'HR',102,200);

-- Insert records into EMPLOYEES
INSERT INTO EMPLOYEES
VALUES(
1,
'OM',
'PATIL',
'om@gmail.com',
'9876543210',
TO_DATE('10-01-2024','DD-MM-YYYY'),
'IT01',
50000,
0.2,
101,
1
);

INSERT INTO EMPLOYEES
VALUES(
2,
'KRUSHNA',
'JADHAV',
'krushna@gmail.com',
'9876543211',
TO_DATE('12-02-2024','DD-MM-YYYY'),
'HR01',
40000,
0.1,
102,
2
);

-- Create EMPTEST table from EMPLOYEES
CREATE TABLE EMPTEST
AS
SELECT *
FROM EMPLOYEES;

-- Add new row into EMPTEST
INSERT INTO EMPTEST
VALUES(
3,
USER,
'SHINDE',
'user@gmail.com',
'9876543222',
TO_DATE('15-03-2024','DD-MM-YYYY'),
'IT02',
45000,
0.2,
103,
1
);

-- Increase salary of OM by 15%
UPDATE EMPTEST
SET SALARY=SALARY+(SALARY*0.15)
WHERE FIRST_NAME='OM';

-- Confirm changes
SELECT *
FROM EMPTEST
WHERE FIRST_NAME='OM';


-- Increase all employee salaries by 10%
UPDATE EMPTEST
SET SALARY=SALARY+(SALARY*0.10);

-- Delete commission data
UPDATE EMPTEST
SET COMMISSION_PCT=NULL;

-- Delete employees in department 10
DELETE FROM EMPTEST
WHERE DEPARTMENT_ID=10;

-- Rollback changes
ROLLBACK;

-- Display EMPTEST table
SELECT *
FROM EMPTEST;


SQL SET 7

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25) NOT NULL,
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10) NOT NULL,
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4)
);

-- Sample records for execution
INSERT INTO EMPLOYEES
VALUES(
1,
'OM',
'PATIL',
'om@gmail.com',
'9876543210',
TO_DATE('10-01-2024','DD-MM-YYYY'),
'IT01',
50000,
0.2,
101,
1
);

INSERT INTO EMPLOYEES
VALUES(
2,
'KRUSHNA',
'JADHAV',
'krushna@gmail.com',
'9876543211',
TO_DATE('12-02-2024','DD-MM-YYYY'),
'HR01',
40000,
0.1,
102,
2
);

-- Start transaction and insert new employee record
INSERT INTO EMPLOYEES
VALUES(
3,
'RAHUL',
'SHINDE',
'rahul@gmail.com',
'9876543222',
TO_DATE('15-03-2024','DD-MM-YYYY'),
'IT02',
45000,
0.2,
103,
1
);

-- Commit transaction
COMMIT;

-- Update employee salary
UPDATE EMPLOYEES
SET SALARY=SALARY+5000
WHERE EMPLOYEE_ID=1;

-- Rollback changes
ROLLBACK;

-- Create savepoint
SAVEPOINT SP1;

-- Update salary
UPDATE EMPLOYEES
SET SALARY=SALARY+2000
WHERE EMPLOYEE_ID=2;

-- Rollback to savepoint
ROLLBACK TO SP1;

-- Create savepoint A
SAVEPOINT A;

-- Update salary
UPDATE EMPLOYEES
SET SALARY=SALARY+1000
WHERE EMPLOYEE_ID=1;

-- Create savepoint B
SAVEPOINT B;

-- Update salary
UPDATE EMPLOYEES
SET SALARY=SALARY+2000
WHERE EMPLOYEE_ID=2;

-- Rollback to savepoint B
ROLLBACK TO B;

-- Delete employee record
DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID=2;

-- Commit changes
COMMIT;





SQL SET 8

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25) NOT NULL,
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10) NOT NULL,
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4)
);

-- Sample records for execution
INSERT INTO EMPLOYEE
VALUES(
1,
'OM',
'PATIL',
'om@gmail.com',
'9876543210',
TO_DATE('10-01-2024','DD-MM-YYYY'),
'IT01',
50000,
0.2,
101,
1
);

INSERT INTO EMPLOYEE
VALUES(
2,
'KRUSHNA',
'JADHAV',
'krushna@gmail.com',
'9876543211',
TO_DATE('12-02-2024','DD-MM-YYYY'),
'HR01',
70000,
0.1,
102,
2
);

INSERT INTO EMPLOYEE
VALUES(
3,
'RAHUL',
'SHINDE',
'rahul@gmail.com',
'9876543222',
TO_DATE('15-03-2024','DD-MM-YYYY'),
'IT02',
45000,
0.2,
101,
1
);

INSERT INTO EMPLOYEE
VALUES(
4,
'AMIT',
'KALE',
'amit@gmail.com',
'9876543233',
TO_DATE('20-04-2024','DD-MM-YYYY'),
'SALES01',
90000,
0.3,
103,
3
);

-- Find highest, lowest, sum and average salar
SELECT
MAX(SALARY) AS HIGHEST_SALARY,
MIN(SALARY) AS LOWEST_SALARY,
SUM(SALARY) AS TOTAL_SALARY,
AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE;

-- Display number of employees with same job
SELECT JOB_ID,
COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY JOB_ID;

-- Determine number of managers without listing them
SELECT COUNT(DISTINCT MANAGER_ID)
AS NUMBER_OF_MANAGERS
FROM EMPLOYEE;

-- Find difference between highest and lowest salary
SELECT
MAX(SALARY)-MIN(SALARY)
AS DIFFERENCE
FROM EMPLOYEE;

-- Display manager number and salary of lowest paid employee under that manager
SELECT MANAGER_ID,
MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEE
GROUP BY MANAGER_ID;


SQL SET 9

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE(
EMP_ID NUMBER,
EMP_NAME VARCHAR2(20),
DEPARTMENT VARCHAR2(20),
CITY VARCHAR2(20),
SALARY NUMBER
);

-- Sample records for execution
INSERT INTO EMPLOYEE
VALUES(101,'OM','IT','PUNE',50000);

INSERT INTO EMPLOYEE
VALUES(102,'KRUSHNA','IT','MUMBAI',60000);

INSERT INTO EMPLOYEE
VALUES(103,'RAHUL','HR','NAGAR',45000);

INSERT INTO EMPLOYEE
VALUES(104,'AMIT','IT','PUNE',70000);

INSERT INTO EMPLOYEE
VALUES(105,'ROHAN','SALES','SATARA',35000);

INSERT INTO EMPLOYEE
VALUES(106,'NIKHIL','HR','DELHI',40000);

INSERT INTO EMPLOYEE
VALUES(107,'AKASH','IT','PUNE',55000);

INSERT INTO EMPLOYEE
VALUES(108,'SUMIT','SALES','NAGPUR',30000);

-- Display department-wise total salary
SELECT DEPARTMENT,
SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT;

-- Display department-wise average salary
SELECT DEPARTMENT,
AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT;

-- Display city-wise employee count greater than 3
SELECT CITY,
COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY CITY
HAVING COUNT(*)>3;

-- Display department-wise maximum salary above 60000
SELECT DEPARTMENT,
MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING MAX(SALARY)>60000;

-- Display department and city-wise total salary
SELECT DEPARTMENT,
CITY,
SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT,CITY;

-- Display departments having more than one employee
SELECT DEPARTMENT,
COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(*)>1;

-- Display city-wise employee count in descending order
SELECT CITY,
COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY CITY
ORDER BY COUNT(*) DESC;


SQL SET 10

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE(
EMP_ID NUMBER,
EMP_NAME VARCHAR2(20),
DEPARTMENT VARCHAR2(20),
CITY VARCHAR2(20),
SALARY NUMBER
);

-- Sample records for execution
INSERT INTO EMPLOYEE
VALUES(101,'OM','IT','PUNE',50000);

INSERT INTO EMPLOYEE
VALUES(102,'KRUSHNA','IT','PUNE',70000);

INSERT INTO EMPLOYEE
VALUES(103,'RAHUL','HR','MUMBAI',45000);

INSERT INTO EMPLOYEE
VALUES(104,'AMIT','HR','MUMBAI',55000);

INSERT INTO EMPLOYEE
VALUES(105,'ROHAN','SALES','PUNE',80000);

INSERT INTO EMPLOYEE
VALUES(106,'NIKHIL','IT','NAGAR',65000);

INSERT INTO EMPLOYEE
VALUES(107,'AKASH','SALES','PUNE',30000);

INSERT INTO EMPLOYEE
VALUES(108,'SUMIT','HR','DELHI',40000);

INSERT INTO EMPLOYEE
VALUES(109,'VISHAL','IT','PUNE',60000);

INSERT INTO EMPLOYEE
VALUES(110,'SAGAR','IT','PUNE',75000);



-- Display department-wise total salary greater than 200000
SELECT DEPARTMENT,
SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>200000;

-- Display department-wise average salary greater than 40000
SELECT DEPARTMENT,
AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING AVG(SALARY)>40000;

-- Display city-wise number of employees
SELECT CITY,
COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY CITY;

-- Display department-wise maximum salary
SELECT DEPARTMENT,
MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT;

-- Display city-wise average salary
SELECT CITY,
AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE
GROUP BY CITY;



-- Display department-wise employee count where employees are more than 3
SELECT DEPARTMENT,
COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(*)>3;

-- Display city-wise employee count in ascending order
SELECT CITY,
COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY CITY
ORDER BY COUNT(*) ASC;



SQL SET 11

-- Create DEPT1 table
CREATE TABLE DEPT1(
DEPTNO INTEGER PRIMARY KEY,
DNAME VARCHAR2(30) NOT NULL,
LOC VARCHAR2(30) NOT NULL
);

-- Add MGR column in DEPT1 table
ALTER TABLE DEPT1
ADD MGR NUMBER;

-- Create EMPL table
CREATE TABLE EMPL(
EMPNO INTEGER,
ENAME VARCHAR2(20),
SAL NUMBER(10,2),
DEPTNO NUMBER
);

-- Add primary key on EMPNO
ALTER TABLE EMPL
ADD CONSTRAINT PK_EMPL
PRIMARY KEY(EMPNO);

-- Add NOT NULL constraint on ENAME
ALTER TABLE EMPL
MODIFY ENAME VARCHAR2(20) NOT NULL;

-- Add CHECK constraint on SAL
ALTER TABLE EMPL
ADD CONSTRAINT CHK_SAL
CHECK(SAL>10000);

-- Add foreign key on DEPTNO
ALTER TABLE EMPL
ADD CONSTRAINT FK_DEPT
FOREIGN KEY(DEPTNO)
REFERENCES DEPT1(DEPTNO);

-- Create DEPT11 table from DEPT1
CREATE TABLE DEPT11
AS
SELECT *
FROM DEPT1;

-- Create EMP11 table from EMPL
CREATE TABLE EMP11
AS
SELECT *
FROM EMPL;

-- Add ADDRESS column in EMPL table
ALTER TABLE EMPL
ADD ADDRESS VARCHAR2(30);

-- Rename SAL column to SALARY
ALTER TABLE EMPL
RENAME COLUMN SAL TO SALARY;

-- Display constraints of EMPL table
SELECT CONSTRAINT_NAME,
CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMPL';


SQL SET 12

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25) NOT NULL,
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10) NOT NULL,
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4)
);


-- Create DEPARTMENTS table
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID NUMBER(4),
DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
MANAGER_ID NUMBER(6),
LOCATION_ID NUMBER(4)
);

-- Sample records for execution
INSERT INTO DEPARTMENTS
VALUES(10,'HR',101,1000);

INSERT INTO DEPARTMENTS
VALUES(20,'SALES',102,2000);

INSERT INTO DEPARTMENTS
VALUES(30,'IT',103,3000);

INSERT INTO EMPLOYEES
VALUES(
1,
'OM',
'PATIL',
'om@gmail.com',
'9876543210',
TO_DATE('10-01-2024','DD-MM-YYYY'),
'SALESMAN',
50000,
0.2,
101,
20
);


INSERT INTO EMPLOYEES
VALUES(
2,
'KRUSHNA',
'JADHAV',
'krushna@gmail.com',
'9876543211',
TO_DATE('12-02-2024','DD-MM-YYYY'),
'HR01',
40000,
0.1,
102,
10
);

INSERT INTO EMPLOYEES
VALUES(
3,
'RAHUL',
'SHINDE',
'rahul@gmail.com',
'9876543222',
TO_DATE('15-03-2024','DD-MM-YYYY'),
'MANAGER',
70000,
0.2,
103,
30
);

-- Display EMPNO, ENAME, SAL, DNAME and LOC using NATURAL JOIN
SELECT EMPLOYEE_ID,
FIRST_NAME,
SALARY,
DEPARTMENT_NAME,
LOCATION_ID
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS;

-- Display JOB, MGR, SAL, COMM and DNAME of employees whose job is SALESMAN
SELECT JOB_ID,
MANAGER_ID,
SALARY,
COMMISSION_PCT,
DEPARTMENT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS
WHERE JOB_ID='SALESMAN';

-- Display ENAME, JOB, DEPTNO and DNAME of employees working in DALLAS
SELECT FIRST_NAME,
JOB_ID,
DEPARTMENT_ID,
DEPARTMENT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS
WHERE LOCATION_ID='DALLAS';

-- Display all employees including KING who has no manager
SELECT EMPLOYEE_ID,
FIRST_NAME,
MANAGER_ID,
DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY EMPLOYEE_ID;

SQL SET 13

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25) NOT NULL,
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10) NOT NULL,
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4)
);

-- Create DEPARTMENTS table
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID NUMBER(4),
DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
MANAGER_ID NUMBER(6),
LOCATION_ID NUMBER(4)
);

-- Sample records for execution
INSERT INTO DEPARTMENTS
VALUES(10,'HR',101,1000);

INSERT INTO DEPARTMENTS
VALUES(20,'SALES',102,2000);

INSERT INTO DEPARTMENTS
VALUES(30,'IT',103,3000);

INSERT INTO EMPLOYEES
VALUES(
1,
'OM',
'PATIL',
'om@gmail.com',
'9876543210',
TO_DATE('10-01-2024','DD-MM-YYYY'),
'SALESMAN',
2500,
0.2,
101,
20
);

INSERT INTO EMPLOYEES
VALUES(
2,
'KRUSHNA',
'JADHAV',
'krushna@gmail.com',
'9876543211',
TO_DATE('12-02-2024','DD-MM-YYYY'),
'HR01',
4500,
0.1,
102,
10
);

INSERT INTO EMPLOYEES
VALUES(
3,
'RAHUL',
'SHINDE',
'rahul@gmail.com',
'9876543222',
TO_DATE('15-03-2024','DD-MM-YYYY'),
'CLERK',
1500,
0.2,
103,
30
);

-- Display name, job, department name, salary and grade
SELECT FIRST_NAME,
JOB_ID,
DEPARTMENT_NAME,
SALARY,
CASE
WHEN SALARY>=5000 THEN 'A'
WHEN SALARY>=3000 THEN 'B'
ELSE 'C'
END AS GRADE
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS;

-- Display ENAME, SAL, MGR and DNAME of employees whose salary >2000 using ON clause
SELECT FIRST_NAME,
SALARY,
MANAGER_ID,
DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE SALARY>2000;

-- Display EMPNO, ENAME, JOB, DEPTNO, DNAME and LOC using LEFT OUTER JOIN
SELECT EMPLOYEE_ID,
FIRST_NAME,
JOB_ID,
E.DEPARTMENT_ID,
DEPARTMENT_NAME,
LOCATION_ID
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

-- Display ENAME and DNAME using RIGHT OUTER JOIN
SELECT FIRST_NAME,
DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

-- Display EMPNO, DNAME and LOC using FULL OUTER JOIN
SELECT EMPLOYEE_ID,
DEPARTMENT_NAME,
LOCATION_ID
FROM EMPLOYEES E
FULL OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;








SQL SET 14

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25) NOT NULL,
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10) NOT NULL,
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4)
);

-- Create DEPARTMENTS table
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID NUMBER(4),
DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
MANAGER_ID NUMBER(6),
LOCATION_ID NUMBER(4)
);

-- Sample records for execution
INSERT INTO DEPARTMENTS
VALUES(10,'HR',101,1000);

INSERT INTO DEPARTMENTS
VALUES(20,'SALES',102,2000);

INSERT INTO DEPARTMENTS
VALUES(30,'IT',103,3000);

INSERT INTO DEPARTMENTS
VALUES(40,'ADMIN',104,4000);

INSERT INTO EMPLOYEES
VALUES(
1,
'OM',
'PATIL',
'om@gmail.com',
'9876543210',
TO_DATE('10-01-2024','DD-MM-YYYY'),
'SALESMAN',
5000,
0.2,
101,
20
);

INSERT INTO EMPLOYEES
VALUES(
2,
'KRUSHNA',
'JADHAV',
'krushna@gmail.com',
'9876543211',
TO_DATE('12-02-2024','DD-MM-YYYY'),
'CLERK',
4500,
0.1,
102,
10
);

INSERT INTO EMPLOYEES
VALUES(
3,
'RAHUL',
'SHINDE',
'rahul@gmail.com',
'9876543222',
TO_DATE('15-03-2024','DD-MM-YYYY'),
'MANAGER',
7000,
0.2,
103,
30
);

-- Display JOB, MGR, SAL, COMM and DNAME of employees whose job is SALESMAN
SELECT JOB_ID,
MANAGER_ID,
SALARY,
COMMISSION_PCT,
DEPARTMENT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS
WHERE JOB_ID='SALESMAN';

-- Display ENAME, JOB, DEPTNO and DNAME of employees working in Pune
SELECT FIRST_NAME,
JOB_ID,
DEPARTMENT_ID,
DEPARTMENT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS
WHERE LOCATION_ID='PUNE';

-- Display employee and department details including departments without employees
SELECT FIRST_NAME,
DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

-- Display employees and departments including employees without department
SELECT FIRST_NAME,
DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

-- Display EMPNO, ENAME and LOC of employees working as CLERK
SELECT EMPLOYEE_ID,
FIRST_NAME,
LOCATION_ID
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS
WHERE JOB_ID='CLERK';


SQL SET 20

-- Create STUDENT table
CREATE TABLE STUDENT(
S_ID NUMBER PRIMARY KEY,
NAME VARCHAR2(20),
DEPT_NAME VARCHAR2(20),
TOT_CRED NUMBER
);


-- Create INSTRUCTOR table
CREATE TABLE INSTRUCTOR(
T_ID NUMBER PRIMARY KEY,
NAME VARCHAR2(20),
DEPT_NAME VARCHAR2(20),
SALARY NUMBER
);

-- Create COURSE table
CREATE TABLE COURSE(
COURSE_ID NUMBER PRIMARY KEY,
TITLE VARCHAR2(20),
DEPT_NAME VARCHAR2(20),
CREDITS NUMBER
);

-- Create TAKES table
CREATE TABLE TAKES(
S_ID NUMBER,
COURSE_ID NUMBER,
FOREIGN KEY(S_ID)
REFERENCES STUDENT(S_ID),
FOREIGN KEY(COURSE_ID)
REFERENCES COURSE(COURSE_ID)
);

-- Insert records into STUDENT
INSERT INTO STUDENT
VALUES(1,'AMOL','COMPUTER',20);

INSERT INTO STUDENT
VALUES(2,'AMIT','IT',18);


INSERT INTO STUDENT
VALUES(3,'SAM','COMPUTER',22);

INSERT INTO STUDENT
VALUES(4,'RAHUL','ENTC',15);

INSERT INTO STUDENT
VALUES(5,'ROHAN','COMPUTER',25);

-- Insert records into INSTRUCTOR
INSERT INTO INSTRUCTOR
VALUES(101,'RAHUL','COMPUTER',50000);

INSERT INTO INSTRUCTOR
VALUES(102,'OM','IT',35000);

INSERT INTO INSTRUCTOR
VALUES(103,'KRUSHNA','COMPUTER',60000);

INSERT INTO INSTRUCTOR
VALUES(104,'AMIT','ENTC',45000);

INSERT INTO INSTRUCTOR
VALUES(105,'AMOL','COMPUTER',55000);

-- Insert records into COURSE
INSERT INTO COURSE
VALUES(1,'DBMS','COMPUTER',4);

INSERT INTO COURSE
VALUES(2,'JAVA','IT',3);

INSERT INTO COURSE
VALUES(3,'CN','COMPUTER',4);

INSERT INTO COURSE
VALUES(4,'OS','IT',3);

INSERT INTO COURSE
VALUES(5,'TOC','ENTC',2);

-- Insert records into TAKES
INSERT INTO TAKES
VALUES(1,1);

INSERT INTO TAKES
VALUES(3,1);

INSERT INTO TAKES
VALUES(2,2);

INSERT INTO TAKES
VALUES(5,1);

INSERT INTO TAKES
VALUES(4,5);

-- i. Find average salary of departments where average salary > 42000
SELECT DEPT_NAME,
AVG(SALARY) AS AVERAGE_SALARY
FROM INSTRUCTOR
GROUP BY DEPT_NAME
HAVING AVG(SALARY)>42000;

-- ii. Increase salary of COMPUTER department instructors by 10%
UPDATE INSTRUCTOR
SET SALARY=SALARY+(SALARY*0.10)
WHERE DEPT_NAME='COMPUTER';

-- iii. Find instructors whose names are neither AMOL nor AMIT
SELECT NAME
FROM INSTRUCTOR
WHERE NAME NOT IN ('AMOL','AMIT');

-- iv. Find students whose names contain 'am'
SELECT NAME
FROM STUDENT
WHERE NAME LIKE '%AM%';

-- v. Find COMPUTER department students taking DBMS course
SELECT S.NAME
FROM STUDENT S
JOIN TAKES T
ON S.S_ID=T.S_ID
JOIN COURSE C
ON T.COURSE_ID=C.COURSE_ID
WHERE S.DEPT_NAME='COMPUTER'
AND C.TITLE='DBMS';


SQL SET 23

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25) NOT NULL,
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10) NOT NULL,
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4)
);

-- Create DEPARTMENTS table
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID NUMBER(4),
DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
MANAGER_ID NUMBER(6),
LOCATION_ID NUMBER(4)
);

-- Insert 5 records into DEPARTMENTS
INSERT INTO DEPARTMENTS
VALUES(10,'HR',101,1000);

INSERT INTO DEPARTMENTS
VALUES(20,'SALES',102,2000);

INSERT INTO DEPARTMENTS
VALUES(30,'IT',103,3000);

INSERT INTO DEPARTMENTS
VALUES(40,'ADMIN',104,4000);

INSERT INTO DEPARTMENTS
VALUES(50,'ACCOUNT',105,5000);

-- Insert 5 records into EMPLOYEES
INSERT INTO EMPLOYEES
VALUES(
1,
'ALLEN',
'PATIL',
'allen@gmail.com',
'9876543210',
TO_DATE('12-05-2022','DD-MM-YYYY'),
'CLERK',
30000,
0.2,
101,
10
);

INSERT INTO EMPLOYEES
VALUES(
2,
'MARTIN',
'JADHAV',
'martin@gmail.com',
'9876543211',
TO_DATE('10-04-2021','DD-MM-YYYY'),
'MANAGER',
50000,
0.3,
102,
20
);

INSERT INTO EMPLOYEES
VALUES(
3,
'KING',
'SHINDE',
'king@gmail.com',
'9876543212',
TO_DATE('15-03-2020','DD-MM-YYYY'),
'SALESMAN',
70000,
0.4,
103,
30
);

INSERT INTO EMPLOYEES
VALUES(
4,
'BLAKE',
'KALE',
'blake@gmail.com',
'9876543213',
TO_DATE('20-02-2023','DD-MM-YYYY'),
'CLERK',
40000,
0.2,
104,
40
);

INSERT INTO EMPLOYEES
VALUES(
5,
'JONES',
'PATIL',
'jones@gmail.com',
'9876543214',
TO_DATE('01-01-2021','DD-MM-YYYY'),
'HR',
35000,
0.1,
105,
50
);

-- 1. List employees whose salary is greater than salary of ALLEN
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY>
(
SELECT SALARY
FROM EMPLOYEES
WHERE FIRST_NAME='ALLEN'
);

-- 2. Find employees whose job is same as MARTIN
SELECT FIRST_NAME,JOB_ID
FROM EMPLOYEES
WHERE JOB_ID=
(
SELECT JOB_ID
FROM EMPLOYEES
WHERE FIRST_NAME='MARTIN'
);

-- 3. Display employees not working in department of KING
SELECT FIRST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID<>
(
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE FIRST_NAME='KING'
);


-- 4. Find employees earning more than BLAKE
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY>
(
SELECT SALARY
FROM EMPLOYEES
WHERE FIRST_NAME='BLAKE'
);

-- 5. Display employees hired after JONES
SELECT FIRST_NAME,HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE>
(
SELECT HIRE_DATE
FROM EMPLOYEES
WHERE FIRST_NAME='JONES'
);

-- 6. Find employees whose department number is same as CLARK
SELECT FIRST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID=
(
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE FIRST_NAME='CLARK'
);





SQL SET 24

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25) NOT NULL,
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10) NOT NULL,
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4)
);

-- Create DEPARTMENTS table
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID NUMBER(4),
DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
MANAGER_ID NUMBER(6),
LOCATION_ID NUMBER(4)
);

-- Insert 5 records into DEPARTMENTS
INSERT INTO DEPARTMENTS
VALUES(10,'HR',101,1000);

INSERT INTO DEPARTMENTS
VALUES(20,'SALES',102,2000);

INSERT INTO DEPARTMENTS
VALUES(30,'IT',103,3000);

INSERT INTO DEPARTMENTS
VALUES(40,'ADMIN',104,4000);

INSERT INTO DEPARTMENTS
VALUES(50,'ACCOUNT',105,5000);

-- Insert 5 records into EMPLOYEES

INSERT INTO EMPLOYEES
VALUES(
1,
'ALLEN',
'PATIL',
'allen@gmail.com',
'9876543210',
TO_DATE('12-05-2022','DD-MM-YYYY'),
'CLERK',
30000,
0.2,
101,
10
);

INSERT INTO EMPLOYEES
VALUES(
2,
'MARTIN',
'JADHAV',
'martin@gmail.com',
'9876543211',
TO_DATE('10-04-2021','DD-MM-YYYY'),
'MANAGER',
50000,
0.3,
102,
20
);

INSERT INTO EMPLOYEES
VALUES(
3,
'KING',
'SHINDE',
'king@gmail.com',
'9876543212',
TO_DATE('15-03-2020','DD-MM-YYYY'),
'SALESMAN',
70000,
0.4,
103,
30
);

INSERT INTO EMPLOYEES
VALUES(
4,
'BLAKE',
'KALE',
'blake@gmail.com',
'9876543213',
TO_DATE('20-02-2023','DD-MM-YYYY'),
'CLERK',
40000,
0.2,
104,
40
);

INSERT INTO EMPLOYEES
VALUES(
5,
'JONES',
'PATIL',
'jones@gmail.com',
'9876543214',
TO_DATE('01-01-2021','DD-MM-YYYY'),
'MANAGER',
35000,
0.1,
105,
20
);

-- 1. Find employees whose salary is greater than ANY employee in department 30
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY > ANY
(
SELECT SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID=30
);

-- 2. Display employees whose salary is greater than ALL employees in department 20
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY > ALL
(
SELECT SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID=20);

-- 3. List employees working in departments where the job is MANAGER
SELECT FIRST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN
(
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID='MANAGER'
);

-- 4. Find employees whose salary is greater than average salary of their department
SELECT FIRST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES E
WHERE SALARY >
(
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID=E.DEPARTMENT_ID
);

-- 5. Display employees earning highest salary in their department
SELECT FIRST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES E
WHERE SALARY=
(
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID=E.DEPARTMENT_ID
);

-- 6. Find employees having same job as at least one employee in department 20
SELECT FIRST_NAME,JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN
(
SELECT JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID=20
);


SQL SET 34

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE(
EMPLOYEE_NAME VARCHAR2(30),
STREET VARCHAR2(30),
CITY VARCHAR2(30)
);

-- Create WORKS table
CREATE TABLE WORKS(
EMPLOYEE_NAME VARCHAR2(30),
COMPANY_NAME VARCHAR2(30),
SALARY NUMBER
);

-- Create COMPANY table
CREATE TABLE COMPANY(
COMPANY_NAME VARCHAR2(30),
CITY VARCHAR2(30)
);

-- Create MANAGES table
CREATE TABLE MANAGES(
EMPLOYEE_NAME VARCHAR2(30),
MANAGER_NAME VARCHAR2(30));

-- Insert records into EMPLOYEE
INSERT INTO EMPLOYEE
VALUES('OM','FC ROAD','PUNE');

INSERT INTO EMPLOYEE
VALUES('KRUSHNA','MG ROAD','MUMBAI');

INSERT INTO EMPLOYEE
VALUES('JONES','JM ROAD','PUNE');

INSERT INTO EMPLOYEE
VALUES('AMIT','RING ROAD','DELHI');

INSERT INTO EMPLOYEE
VALUES('RAHUL','COLLEGE ROAD','PUNE');

-- Insert records into COMPANY
INSERT INTO COMPANY
VALUES('First Bank Corporation','PUNE');

INSERT INTO COMPANY
VALUES('Small Bank Corporation','MUMBAI');

INSERT INTO COMPANY
VALUES('TCS','DELHI');

INSERT INTO COMPANY
VALUES('INFOSYS','PUNE');

INSERT INTO COMPANY
VALUES('WIPRO','NAGPUR');


-- Insert records into WORKS
INSERT INTO WORKS
VALUES('OM','First Bank Corporation',15000);

INSERT INTO WORKS
VALUES('KRUSHNA','Small Bank Corporation',9000);

INSERT INTO WORKS
VALUES('JONES','First Bank Corporation',20000);

INSERT INTO WORKS
VALUES('AMIT','TCS',12000);

INSERT INTO WORKS
VALUES('RAHUL','First Bank Corporation',18000);

-- Insert records into MANAGES
INSERT INTO MANAGES
VALUES('OM','JONES');

INSERT INTO MANAGES
VALUES('KRUSHNA','OM');

INSERT INTO MANAGES
VALUES('AMIT','JONES');

INSERT INTO MANAGES
VALUES('RAHUL','OM');

INSERT INTO MANAGES
VALUES('JONES','RAHUL');



-- 1. Find employees working for First Bank Corporation
SELECT EMPLOYEE_NAME
FROM WORKS
WHERE COMPANY_NAME='First Bank Corporation';

-- 2. Find employee names and cities working for First Bank Corporation
SELECT E.EMPLOYEE_NAME,E.CITY
FROM EMPLOYEE E
JOIN WORKS W
ON E.EMPLOYEE_NAME=W.EMPLOYEE_NAME
WHERE W.COMPANY_NAME='First Bank Corporation';

-- 3. Find employee names, street addresses and cities earning more than 10000 in First Bank Corporation
SELECT E.EMPLOYEE_NAME,E.STREET,E.CITY
FROM EMPLOYEE E
JOIN WORKS W
ON E.EMPLOYEE_NAME=W.EMPLOYEE_NAME
WHERE W.COMPANY_NAME='First Bank Corporation'
AND W.SALARY>10000;

-- 4. Find employees living in same city as company
SELECT E.EMPLOYEE_NAME
FROM EMPLOYEE E
JOIN WORKS W
ON E.EMPLOYEE_NAME=W.EMPLOYEE_NAME
JOIN COMPANY C
ON W.COMPANY_NAME=C.COMPANY_NAME
WHERE E.CITY=C.CITY;

-- 5. Find employees living on same street and city as manager
SELECT E.EMPLOYEE_NAME
FROM EMPLOYEE E
JOIN MANAGES M
ON E.EMPLOYEE_NAME=M.EMPLOYEE_NAME
JOIN EMPLOYEE MGR
ON M.MANAGER_NAME=MGR.EMPLOYEE_NAME
WHERE E.STREET=MGR.STREET
AND E.CITY=MGR.CITY;

-- 6. Find employees not working for First Bank Corporation
SELECT EMPLOYEE_NAME
FROM WORKS
WHERE COMPANY_NAME<>'First Bank Corporation';

-- 7. Give all employees of First Bank Corporation a 10% raise
UPDATE WORKS
SET SALARY=SALARY+(SALARY*0.10)
WHERE COMPANY_NAME='First Bank Corporation';

-- 8. Delete tuples in WORKS relation for employees of Small Bank Corporation
DELETE FROM WORKS
WHERE COMPANY_NAME='Small Bank Corporation';


SQL SET 35

-- 1. Find employees earning more than each employee of Small Bank Corporation
SELECT EMPLOYEE_NAME
FROM WORKS
WHERE SALARY > ALL
(
SELECT SALARY
FROM WORKS
WHERE COMPANY_NAME='Small Bank Corporation'
);



-- 2. Find companies located in every city where Small Bank Corporation is located
SELECT COMPANY_NAME
FROM COMPANY
WHERE CITY IN
(
SELECT CITY
FROM COMPANY
WHERE COMPANY_NAME='Small Bank Corporation'
);

-- 3. Find employees earning more than average salary of their company
SELECT EMPLOYEE_NAME,SALARY
FROM WORKS W
WHERE SALARY >
(
SELECT AVG(SALARY)
FROM WORKS
WHERE COMPANY_NAME=W.COMPANY_NAME
);

-- 4. Find company having most employees
SELECT COMPANY_NAME
FROM WORKS
GROUP BY COMPANY_NAME
HAVING COUNT(*)=
(
SELECT MAX(COUNT(*))
FROM WORKS
GROUP BY COMPANY_NAME
);

-- 5. Find company having smallest payroll
SELECT COMPANY_NAME
FROM WORKS
GROUP BY COMPANY_NAME
HAVING SUM(SALARY)=
(
SELECT MIN(SUM(SALARY))
FROM WORKS
GROUP BY COMPANY_NAME
);

-- 6. Find companies whose average salary is greater than First Bank Corporation
SELECT COMPANY_NAME
FROM WORKS
GROUP BY COMPANY_NAME
HAVING AVG(SALARY)>
(
SELECT AVG(SALARY)
FROM WORKS
WHERE COMPANY_NAME='First Bank Corporation'
);

-- 7. Update city of JONES to Newtown
UPDATE EMPLOYEE
SET CITY='NEWTOWN'
WHERE EMPLOYEE_NAME='JONES';


